movies = [
    {"title": "Interstellar", "description": "A farmer and ex-NASA pilot travels through a wormhole in search of a new planet to save humanity from extinction."},
    {"title": "The Dark Knight", "description": "Batman battles a psychopathic criminal called the Joker who wants to unleash chaos and anarchy upon Gotham City."},
    {"title": "Inception", "description": "A thief who enters people's dreams to steal secrets is given the task of planting an idea into someone's mind."},
    {"title": "The Shawshank Redemption", "description": "A banker is wrongly convicted of murder and builds an unlikely friendship while enduring years in a brutal prison."},
    {"title": "Parasite", "description": "A poor family cleverly infiltrates the lives of a wealthy household, leading to a shocking and dark chain of events."},
    {"title": "Get Out", "description": "A Black man visits his white girlfriend's family estate and slowly uncovers a disturbing and sinister secret."},
    {"title": "Arrival", "description": "A linguist is recruited by the military to communicate with alien spacecraft that have appeared across the globe."},
    {"title": "The Matrix", "description": "A hacker discovers that reality is a simulation and joins a rebellion against the machines controlling humanity."},
    {"title": "Whiplash", "description": "An ambitious young drummer enrolls at a cutthroat music conservatory where he faces an abusive and obsessive instructor."},
    {"title": "Knives Out", "description": "A detective investigates the death of a wealthy crime novelist when the entire eccentric family becomes a suspect."},
    {"title": "Mad Max: Fury Road", "description": "In a post-apocalyptic wasteland, a woman escapes a tyrant with a group of female prisoners and a drifter."},
    {"title": "Her", "description": "A lonely writer develops a deep emotional and romantic relationship with an AI operating system."},
    {"title": "Gone Girl", "description": "A man becomes the prime suspect in his wife's disappearance, as dark secrets about their marriage begin to surface."},
    {"title": "Avengers: Infinity War", "description": "The Avengers and their allies must stop a powerful alien warlord from collecting all six infinity stones."},
    {"title": "Soul", "description": "A jazz musician accidentally falls into the afterlife and must find his way back to Earth before his big performance."},
    {"title": "Prisoners", "description": "A desperate father takes matters into his own hands when police fail to find his kidnapped daughter quickly enough."},
    {"title": "The Grand Budapest Hotel", "description": "A legendary concierge and his young protégé are caught up in a murder mystery and the theft of a priceless painting."},
    {"title": "1917", "description": "Two young British soldiers must cross enemy territory on foot to deliver a message that could save 1600 lives."},
    {"title": "Hereditary", "description": "After a grandmother's death, a family begins to unravel terrifying secrets as a supernatural presence invades their home."},
    {"title": "The Social Network", "description": "The story of how a Harvard student betrayed his best friend and built one of the most powerful companies in the world."},
]